[package]
name = "RustUI"
version = "0.1.0"
edition = "2021"

[dependencies]
glfw = "0.55.0"
gl11 = "0.1.1"
gl = "0.14.0"
winapi = { version = "0.3.9", features = ["wincon", "winuser", "winnt"] }
freetype-rs = "0.36.0"
